<?php

namespace AppBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPromoByCity($cityId){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->join('p.city', 'c')
            ->where('c.id = :cityId')
            ->setParameter('cityId', $cityId);

        return $qb->getQuery()->getResult();
    }
}
